name = "url-monitoring-api"
main = "src/index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = [ "nodejs_compat" ]

[build]
command = "npm run build"

[triggers]
crons = ["*/5 * * * *"]

[vars]
DATABASE_URL = "postgresql://postgres:Indina%2525159@db.xwkbrumvoodhpdovuapr.supabase.co:5432/postgres"
JWT_SECRET = "Xz7Kj9N3!vTqR5bE1pLz2fWgHy"
